### ISSUE TITLE
feature request: 2pages1side

### ISSUE THREAD

**Issue by juxd** [dlqs/SOCprint#10]
you know you want to

from soc wiki:

![image](https://user-images.githubusercontent.com/22497281/110318700-c8374c80-8048-11eb-8b35-9073abbccf94.png)

**Comment by dlqs** [comment]
Our product manager @afterdusk will add this to the run board

**Comment by juxd** [comment]
i'm not sure if `multips` `psnup` `mpage` or `a2ps` are posix compliant

**Comment by dlqs** [comment]
~~who gives a shit~~

**Comment by juxd** [comment]
closed by #12
