### ISSUE TITLE
Faulty file type check

### ISSUE THREAD

**Issue by SuibianP** [dlqs/SOCprint#22]
https://github.com/dlqs/SOCprint/blob/eda8cf172d48214a743b5387a8a2e63a4d994f69/socprint.sh#L263-L264

- gives false positives for filenames containing spaces

- does not enforce the locale setting to be `POSIX`

**Comment by dlqs** [comment]
Hey, thanks for the bug report. I verified the first bug.

I'm not sure if enforcing locale setting a POSIX requirement for the script. afaik the *shell* that the script is running on is should be the one setting the locale settings, e.g. LC_CTYPE environment variables. Are you running into any errors because of that?

**Comment by SuibianP** [comment]
I refer to the POSIX 2017 standard at <https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/>.

It seems that the command should be free to implement i18n features for the output, e.g. `文本` or `テキスト` instead of `text`, though I am not able to replicate with zh_CN.UTF-8 or ja_JP.UTF-8 locales. Might be better to `LC_ALL=POSIX` just to be certain.

Also, `-b` and `--mime-type` are not in POSIX 2017 `file` either.

**Comment by dlqs** [comment]
> It seems that the command should be free to implement i18n features for the output, e.g. 文本 or テキスト instead of text, though I am not able to replicate with zh_CN.UTF-8 or ja_JP.UTF-8 locales. Might be better to LC_ALL=POSIX just to be certain.

I see. Sounds reasonable

> Also, -b and --mime-type are not in POSIX 2017 file either.

Thanks for flagging this! Fix looks gnarly but at least its compliant

**Comment by SuibianP** [comment]
Huge thanks for developing the really convenient script by the way! :1st_place_medal:
