### ISSUE TITLE
[Feature Request] Ability to update locally saved script

### ISSUE THREAD

**Issue by afterdusk** [dlqs/SOCprint#3]
## Problem
Users using locally saved scripts will not receive updates and may encounter bugs already fixed on master.

## Feature Request
1. Detect when script is out-of-date and warn user
2. Provide user with single-line command to update script

**Comment by juxd** [comment]
fixed? @dlqs

**Comment by dlqs** [comment]
- [x] fixed? yes
- [x] tested? absolutely
- [x] hotel? trivago
