### ISSUE TITLE
posix compliance

### ISSUE THREAD

**Issue by dlqs** [dlqs/SOCprint#4]
pls

**Comment by juxd** [comment]
cool bro

**Comment by dlqs** [comment]
Socprint is pleased to announced that as of 7 March 2021, we have completed POSIX™ Certification. This is in line with our Q2 2021 plans to submitted a draft Registration Statement on Form S-1 to the Securities and Exchange Commission  (the “SEC”) relating to the proposed initial public offering of our common stock. The number of shares to be offered and the price range for the proposed offering have not yet been determined. The initial public offering is expected to take place after the SEC completes its review process, subject to market and other conditions.

This press release is being made pursuant to, and in accordance with, Rule 135 under the Securities Act of 1933, as amended (the “Securities Act”), and shall not constitute an offer to sell, or the solicitation of an offer to buy, any securities. Any offers, solicitations or offers to buy, or any sales of securities will be made in accordance with the registration requirements of the Securities Act.
